server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 # 拉取服务的间隔时间
zuul:
  prefix: /api
  routes:
    item-service: /item/** # 路由到商品微服务
    search-service: /search/** # 路由到搜索微服务
    user-service: /user/** # 路由到用户微服务
    auth-service: /auth/** # 路由到授权中心微服务
    cart-service: /cart/** # 路由到购物车微服务
    order-service: /order/** # 路由到订单微服务
  add-host-header: true  # 携带请求本身的host头信息
  sensitive-headers:  # 覆盖默认铭感头信息

leyou:
  # jwt相关配置
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookieName
  filter:
    # 网关过滤白名单
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item