server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
      username: root
      url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.106
  rabbitmq:
    virtual-host: /leyou
    host: 192.168.1.106
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo